spring:
  application:
    name: rabbitmq-springboot
  profiles:
    active: dev2

---
spring:
  rabbitmq:
    host: localhost
    port: 5672 # this 5672 is correct, our rabbit mq console management port is 15672
    username: wong
    password: guest
    virtual-host: /wong
  config:
    activate:
      on-profile: dev

---
spring:
  rabbitmq:
    host: localhost
    port: 5672 # this 5672 is correct, our rabbit mq console management port is 15672
    username: hmall
    password: guest
    virtual-host: /hmall
    listener:
      simple:
        prefetch: 1 # this force the consumer only fetch from the queue when consume finish, thus those higher performance consumer can handle more queue messages
        acknowledge-mode: auto # by default acknowledge mode was auto, we can set it to manual, auto or none
  config:
    activate:
      on-profile: dev2
---